# Generated by Django 4.2.16 on 2024-11-04 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grid.clients.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_settings', '0003_alter_commissionlevel_options_delete_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('company_size', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='logos/', validators=[grid.clients.models.validate_image_size])),
                ('stripe_id', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Pending Approval'), (3, 'Email Verification Pending'), (4, 'Email Verified'), (5, 'Wait list'), (6, 'Rejected')], default=2)),
                ('addresses', models.ManyToManyField(related_name='clients', to='site_settings.address')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='site_settings.country')),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('icon_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientUserProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.SmallIntegerField(choices=[(0, 'Superadmin'), (1, 'Admin'), (2, 'Member')], default=2)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/', validators=[grid.clients.models.validate_image_size])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.industry'),
        ),
    ]
