# Generated by Django 4.2.16 on 2024-11-04 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_remove_client_addresses_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={"ordering": ["name"], "verbose_name_plural": "Industries"},
        ),
    ]
