# Generated by Django 4.2.16 on 2024-11-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_industry_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="linkedin_company_size",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
