# Generated by Django 4.2.16 on 2024-11-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_client_linkedin_company_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="linkedin_company_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
