# Generated by Django 4.2.16 on 2024-11-06 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_alter_address_client"),
        ("clients", "0007_alter_clientuserprofile_user"),
    ]

    operations = []
