# Generated by Django 4.2.16 on 2024-11-08 18:40

from django.db import migrations, models
import django.db.models.deletion
import grid.clients.models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0007_alter_country_options_country_priority"),
        ("clients", "0008_merge_20241106_2214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="site_settings.country"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="industry",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="clients.industry"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                upload_to=grid.clients.models.get_client_logo_path,
                validators=[grid.clients.models.validate_image_size],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Active"),
                    (2, "Pending Approval"),
                    (3, "Pending Signup"),
                    (4, "Wait list"),
                    (5, "Rejected"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clientuserprofile",
            name="profile_photo",
            field=models.ImageField(
                upload_to=grid.clients.models.get_client_profile_photo_path,
                validators=[grid.clients.models.validate_image_size],
            ),
        ),
    ]
