# Generated by Django 4.2.16 on 2024-11-10 20:47

from django.db import migrations, models
import grid.clients.models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_alter_client_country_alter_client_industry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=grid.clients.models.get_client_logo_path,
                validators=[grid.clients.models.validate_image_size],
            ),
        ),
    ]
