# Generated by Django 4.2.16 on 2024-11-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0011_address_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(default="HQ", max_length=255),
        ),
    ]
