# Generated by Django 4.2.16 on 2024-11-14 08:54

from django.db import migrations, models
import grid.clients.models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0012_address_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientuserprofile",
            name="profile_photo",
            field=models.ImageField(
                max_length=255,
                upload_to=grid.clients.models.get_client_profile_photo_path,
                validators=[grid.clients.models.validate_image_size],
            ),
        ),
    ]
