# Generated by Django 4.2.16 on 2024-11-15 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messageattachment",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="MessageAttachment",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
