# Generated by Django 4.2.16 on 2024-11-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="message",
            name="job",
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_files/"),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
