# Generated by Django 4.2.16 on 2024-11-15 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0006_message_attachments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="attachments",
        ),
    ]
