# Generated by Django 4.2.16 on 2024-11-16 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0012_alter_recruiter_agency"),
        ("clients", "0013_alter_clientuserprofile_profile_photo"),
        ("chats", "0007_remove_message_attachments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="participants",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="clients",
            field=models.ManyToManyField(related_name="chat_room", to="clients.client"),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="recruiter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="recruiters.recruiter",
            ),
            preserve_default=False,
        ),
    ]
