# Generated by Django 4.2.16 on 2024-11-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0008_remove_chatroom_participants_chatroom_clients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
