# Generated by Django 4.2.16 on 2024-11-17 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chats", "0009_message_is_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read_by",
            field=models.ManyToManyField(blank=True, related_name="read_messages", to=settings.AUTH_USER_MODEL),
        ),
    ]
