# Generated by Django 4.2.16 on 2024-11-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0013_alter_job_expected_commission_alter_job_signup_bonus_and_more"),
        ("chats", "0010_message_read_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="job",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="jobs.job"),
        ),
    ]
