# Generated by Django 4.2.16 on 2024-11-17 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0011_message_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="name",
        ),
    ]
