# Generated by Django 4.2.16 on 2024-11-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_alter_agency_options_alter_jobcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='priority',
            field=models.IntegerField(default=10),
        ),
    ]
