# Generated by Django 4.2.16 on 2024-11-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0004_jobcategory_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="linkedin",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
