# Generated by Django 4.2.16 on 2024-11-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0004_jobcategory_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="bank_details",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="tax_details",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="agency",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account",
                to="recruiters.agency",
            ),
        ),
        migrations.AddField(
            model_name="taxinformation",
            name="agency",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tax_information",
                to="recruiters.agency",
            ),
        ),
    ]
