# Generated by Django 4.2.16 on 2024-11-06 10:49

from django.db import migrations, models
import grid.recruiters.models


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0005_alter_recruiter_linkedin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos/",
                validators=[grid.recruiters.models.validate_image_size],
            ),
        ),
    ]
