# Generated by Django 4.2.16 on 2024-11-06 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0005_alter_recruiter_linkedin"),
        ("recruiters", "0005_remove_agency_bank_details_remove_agency_tax_details_and_more"),
    ]

    operations = []
