# Generated by Django 4.2.16 on 2024-11-06 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0006_alter_recruiter_profile_photo"),
        ("recruiters", "0007_alter_recruiter_status_alter_recruiter_user"),
    ]

    operations = []
