# Generated by Django 4.2.16 on 2024-11-08 18:40

from django.db import migrations, models
import grid.recruiters.models


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0009_agency_website_alter_recruiter_linkedin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=grid.recruiters.models.get_recruiter_photo_path,
                validators=[grid.recruiters.models.validate_image_size],
            ),
        ),
    ]
