# Generated by Django 4.2.16 on 2024-11-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruiters", "0010_alter_recruiter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
