# Generated by Django 4.2.16 on 2024-11-11 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("site_settings", "0008_alter_state_two_letter_code"),
        ("jobs", "0010_remove_recruiterpayment_currency_and_more"),
        ("recruiters", "0012_alter_recruiter_agency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hire",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("base_salary", models.FloatField()),
                (
                    "payment_status",
                    models.SmallIntegerField(
                        choices=[(0, "Due"), (1, "Paid"), (2, "Refunded"), (3, "Cancelled")], default=0
                    ),
                ),
                ("join_date", models.DateTimeField(blank=True, null=True)),
                ("payout", models.FloatField()),
                ("commission", models.FloatField()),
                ("commission_percentage", models.SmallIntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="hire_candidate", to="jobs.candidate"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="hire_job", to="jobs.job"
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hire_recruiter",
                        to="recruiters.recruiter",
                    ),
                ),
            ],
            options={
                "ordering": ["-join_date"],
            },
        ),
        migrations.CreateModel(
            name="RecruiterPayment",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("amount", models.FloatField()),
                ("due_on", models.DateTimeField()),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Pending"), (1, "Paid"), (2, "Due"), (3, "Cancelled")], default=0
                    ),
                ),
                ("percentage_of_full", models.SmallIntegerField()),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="recruiter_payment",
                        to="site_settings.currency",
                    ),
                ),
                (
                    "hire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="hire_payment", to="hires.hire"
                    ),
                ),
            ],
            options={
                "ordering": ["-due_on"],
            },
        ),
    ]
