# Generated by Django 4.2.16 on 2024-11-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
        ("hires", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hire",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="hire_candidate", to="candidates.candidate"
            ),
        ),
    ]
