# Generated by Django 4.2.16 on 2024-11-11 22:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0008_alter_state_two_letter_code"),
        ("clients", "0010_alter_client_logo"),
        ("hires", "0002_alter_hire_candidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("invoice_code", models.CharField(blank=True, max_length=8, unique=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_address", models.TextField()),
                ("due_date", models.DateTimeField()),
                ("product_name", models.CharField(default="Recruitment Services", max_length=255)),
                ("description", models.TextField(default="Commission for successful hiring of an employee")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_name", models.CharField(default="GST/HST/VAT", max_length=100)),
                ("tax_percentage", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="clients.client"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="site_settings.currency"),
                ),
                (
                    "hire",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invoice", to="hires.hire"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
