# Generated by Django 4.2.16 on 2024-11-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hires", "0003_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.SmallIntegerField(choices=[(1, "Due"), (2, "Paid"), (3, "Void"), (4, "Refunded")], default=1),
        ),
    ]
