# Generated by Django 4.2.16 on 2024-11-04 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0002_profileimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commissionlevel",
            options={"ordering": ["min_commission"]},
        ),
        migrations.DeleteModel(
            name="ProfileImage",
        ),
    ]
