# Generated by Django 4.2.16 on 2024-11-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0006_companysize_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["priority"], "verbose_name_plural": "Countries"},
        ),
        migrations.AddField(
            model_name="country",
            name="priority",
            field=models.IntegerField(default=10),
        ),
    ]
