# Generated by Django 4.2.16 on 2024-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0007_alter_country_options_country_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="state",
            name="two_letter_code",
            field=models.CharField(max_length=4),
        ),
    ]
