# Generated by Django 4.2.16 on 2024-11-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0008_alter_state_two_letter_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="tax_name",
            field=models.CharField(blank=True, default="Tax", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="state",
            name="tax_percentage",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
