# Generated by Django 4.2.16 on 2024-11-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='cancelreason',
            name='priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='language',
            name='priority',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='stage',
            name='priority',
            field=models.IntegerField(default=10),
        ),
    ]
