# Generated by Django 4.2.16 on 2024-11-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_benefit_priority_cancelreason_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_interviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=models.SmallIntegerField(choices=[(0, "Original"), (1, "Formatted"), (2, "Edited")], default=1),
        ),
    ]
