# Generated by Django 4.2.16 on 2024-11-07 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0004_candidate_is_interviewed_candidate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewstep",
            name="priority",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="min_book_of_business",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="JobNotes",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField()),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="jobs.job")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
