# Generated by Django 4.2.16 on 2024-11-08 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_interviewstep_priority_job_min_book_of_business_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="no_of_roles",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1, "No. of roles must be at least 1")]
            ),
        ),
    ]
