# Generated by Django 4.2.16 on 2024-11-11 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_job_no_of_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobattachment",
            name="job",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="jobs.job"),
        ),
    ]
