# Generated by Django 4.2.16 on 2024-11-11 05:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_alter_jobattachment_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobattachment",
            name="id",
        ),
        migrations.AddField(
            model_name="jobattachment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name="created"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobattachment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="jobattachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AddField(
            model_name="jobattachment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
