# Generated by Django 4.2.16 on 2024-11-11 07:31

from django.db import migrations, models
import grid.jobs.models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_remove_jobattachment_id_jobattachment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobattachment",
            name="file",
            field=models.FileField(upload_to="job_attachments/", validators=[grid.jobs.models.validate_file_extension]),
        ),
    ]
