# Generated by Django 4.2.16 on 2024-11-11 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_alter_jobattachment_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruiterpayment",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="recruiterpayment",
            name="hire",
        ),
        migrations.DeleteModel(
            name="Hire",
        ),
        migrations.DeleteModel(
            name="RecruiterPayment",
        ),
    ]
