# Generated by Django 4.2.16 on 2024-11-11 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hires", "0002_alter_hire_candidate"),
        ("jobs", "0010_remove_recruiterpayment_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stagelog",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="stagelog",
            name="from_stage",
        ),
        migrations.RemoveField(
            model_name="stagelog",
            name="to_stage",
        ),
        migrations.RemoveField(
            model_name="stagelog",
            name="user",
        ),
        migrations.DeleteModel(
            name="Candidate",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.DeleteModel(
            name="Stage",
        ),
        migrations.DeleteModel(
            name="StageLog",
        ),
    ]
