# Generated by Django 4.2.16 on 2024-11-14 08:54

from django.db import migrations, models
import grid.jobs.models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0012_remove_messageattachment_message_delete_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="expected_commission",
            field=models.IntegerField(default=0, validators=[grid.jobs.models.validate_expected_commission]),
        ),
        migrations.AlterField(
            model_name="job",
            name="signup_bonus",
            field=models.IntegerField(default=0, validators=[grid.jobs.models.validate_signup_bonus]),
        ),
        migrations.AlterField(
            model_name="job",
            name="stocks_value",
            field=models.IntegerField(default=0, validators=[grid.jobs.models.validate_stock_value]),
        ),
    ]
